name: Dependency analysis with OSV-Scanner

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Environment"
        required: true
        type: string

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies (only for Node.js)
        run: |
          if [ -f "package.json" ]; then
            echo "Node.js project detected. Installing dependencies..."
            npm install
          else
            echo "No Node.js project found. Skipping dependency installation."
          fi

      - name: Generate SPDX SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx
          output-file: sbom.spdx.json
          path: .

      - name: Install OSV-Scanner
        run: |
          wget -qO /usr/local/bin/osv-scanner https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64
          chmod a+x /usr/local/bin/osv-scanner
          osv-scanner --version

      - name: Apply analysis with OSV-Scanner
        id: osv_scan
        run: |
          # Intentamos ejecutar el escaneo, y si falla, seguimos adelante pero generamos el reporte
          osv-scanner scan --format html --sbom=sbom.spdx.json > ${{ github.repository_id }}.html
        continue-on-error: true

      - name: Upload OSV Scanner Report as Artifact
        if: failure()  # Solo sube el archivo si el escaneo falló
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository }}-report-${{ github.sha }}
          path: ${{ github.repository_id }}.html
          retention-days: 1

      - name: Proceed with next steps if no vulnerabilities found
        if: success()  # Continúa con el flujo normal si no hubo fallos
        run: |
          echo "No vulnerabilities found. Proceeding with the next steps."
          
