name: Dependency analysis with OSV-Scanner

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "env"
        required: true
        type: string

permissions:
  contents: read

jobs:
  osv-scanner:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check file existence
        id: check_file
        uses: andstor/file-existence-action@v3
        with:
          files: "package.json"

      - name: Set up Node.js (only if package.json exists)
        if: steps.check_file.outputs.exists == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies (only for Node.js if package.json exists)
        if: steps.check_file.outputs.exists == 'true'
        run: |
          echo "Node.js project detected. Installing dependencies..."
          npm install

      - name: Generate SPDX SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx
          output-file: sbom.spdx.json
          path: .
          upload-artifact: false

      - name: Install OSV-Scanner
        run: |
          wget -qO /usr/local/bin/osv-scanner https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64
          chmod a+x /usr/local/bin/osv-scanner
          osv-scanner --v

      - name: Apply analysis with OSV-Scanner
        run: |
          osv-scanner scan --format html --sbom=sbom.spdx.json > ${{ github.repository_id }}.html

        continue-on-error: true

      - name: Upload OSV-Scanner report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_id }}_report
          path: ${{ github.repository_id }}.html
          retention-days: 1
          