name: Dependency analysis with OSV-Scanner

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "env"
        required: true
        type: string

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies (only for Node.js)
        run: |
          if [ -f "package.json" ]; then
            echo "Node.js project detected. Installing dependencies..."
            npm install
          else
            echo "No Node.js project found. Skipping dependency installation."
          fi

      - name: Generate SPDX SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx
          output-file: sbom.spdx.json
          path: .
          upload-artifact: false

      - name: Install OSV-Scanner
        run: |
          wget -qO /usr/local/bin/osv-scanner https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64
          chmod a+x /usr/local/bin/osv-scanner
          osv-scanner --version

      # - name: Apply analysis with OSV-Scanner
      #   run: |
      #     osv-scanner scan --format html --sbom=sbom.spdx.json > ${{ github.repository_id }}.html
      #   continue-on-error: true

      - name: Test
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.9.1



      - name: Upload OSV Scanner Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.PROJECT_NAME }}_report
          path: ${{ github.repository_id }}.html
          retention-days: 1
